name: Release

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Pre-release
        id: check-pre-release
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "pre-release=false" >> $GITHUB_OUTPUT
          else
              echo "pre-release=true" >> $GITHUB_OUTPUT
          fi
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          append_body: true
          prerelease: ${{ steps.check-pre-release.outputs.pre-release == 'true' }}
