---
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_DIR_PREFIX: test-build
  OPTIMIZATION: 0
  DEBUG: 'true'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        compiler: ['gcc']
    steps:
      - name: Install compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}
      - run: pip install ninja meson
      - uses: actions/checkout@v4
      - run: CC=${{ matrix.compiler }} meson setup --wipe ${{ env.BUILD_DIR_PREFIX }}-${{ matrix.compiler }} -Doptimization=${{ env.OPTIMIZATION }} -Ddebug=${{ env.DEBUG }} -Dtests=true
      - run: CC=${{ matrix.compiler }} meson test -C ${{ env.BUILD_DIR_PREFIX }}-${{ matrix.compiler }} --logbase test-log
      - run: ruby "$(find . -name parse_output.rb -type f)" -xml ${{ env.BUILD_DIR_PREFIX }}-${{ matrix.compiler }}/meson-logs/test-log.txt && mv report.xml ${{ env.BUILD_DIR_PREFIX }}-${{ matrix.compiler }}/meson-logs/test-report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '${{ env.BUILD_DIR_PREFIX }}-${{ matrix.compiler }}/meson-logs/test-report.xml'
