---
name: test

on:
  push:
    branches: [ ${{ github.event.repository.default_branch }} ]
  pull_request:
    branches: [ ${{ github.event.repository.default_branch }} ]

env:
  BUILD_DIR_PREFIX: test-build
  OPTIMIZATION: 0
  DEBUG: 'true'

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        compiler: ['gcc']
    steps:
      - name: Install compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}
      - run: pip install ninja meson
      - uses: actions/checkout@v4
      - run: CC=${{ matrix.compiler }} meson setup --wipe ${{ env.BUILD_DIR_PREFIX }}-${{ matrix.compiler }} -Doptimization=${{ env.OPTIMIZATION }} -Ddebug=${{ env.DEBUG }} -Dtests=true
      - run: CC=${{ matrix.compiler }} meson test -C ${{ env.BUILD_DIR_PREFIX }}-${{ matrix.compiler }}
